import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@ant-design/v5-patch-for-react-19';
import "./globals.css";
import { FloatButton } from 'antd';
import { ConfigProvider, theme } from 'antd';
import Header from "./components/Header";
import Footer from "./components/Footer";
import { WishlistCartProvider } from "./context/WishlistCartContext";
import LangFloatSwitch from "./language";
import GoogleTranslateFloatButton from "./language";

export const dynamic = "force-dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Atrafi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <WishlistCartProvider>
          <AntdRegistry>
            <ConfigProvider
              theme={{
                algorithm: theme.compactAlgorithm,
                token: {
                  colorPrimary: '#357ABD',
                  colorLink: '#000',
                  colorLinkHover: '#000',
                  colorLinkActive: 'blue'
                },
              }}
            >
                <Header />
                {children}
                <GoogleTranslateFloatButton />
                <Footer />
            </ConfigProvider>
          </AntdRegistry>
        </WishlistCartProvider>
      </body>
    </html>
  );
}
